<?php
return [
    'Warning'                                                                                               => 'ご案内',
    'Installing FastAdmin'                                                                                  => 'インストールFastAdmin',
    'Mysql Hostname'                                                                                        => 'MySQL データベースアドレス',
    'Mysql Database'                                                                                        => 'MySQL データベース名',
    'Mysql Username'                                                                                        => 'MySQL ユーザー名',
    'Mysql Password'                                                                                        => 'MySQL パスワード',
    'Mysql Prefix'                                                                                          => 'MySQL テーブル接頭辞',
    'Mysql Hostport'                                                                                        => 'MySQL ポート番号',
    'Admin Username'                                                                                        => '管理者ユーザー名',
    'Admin Email'                                                                                           => '管理者Email',
    'Admin Password'                                                                                        => '管理者パスワード',
    'Repeat Password'                                                                                       => '管理者パスワードを再入力',
    'Website'                                                                                               => 'サイト名',
    'My Website'                                                                                            => 'マイサイト',
    'Install now'                                                                                           => 'クリックしてインストール',
    'Installing'                                                                                            => 'インストール中...',
    'Home'                                                                                                  => 'トップページへアクセス',
    'Dashboard'                                                                                             => '管理画面に入る',
    'Go back'                                                                                               => '前のページに戻る',
    'Install Successed'                                                                                     => 'インストール成功！',
    'Security tips'                                                                                         => 'ご案内：以下の管理画面ログイン入口をお気に入りに追加してください，サイトの安全のために，他人に漏らしたり送信しないでください！漏えいした場合は速やかに変更してください！',
    'Please input correct database'                                                                         => '正しいデータベース名を入力してください',
    'Please input correct username'                                                                         => 'ユーザー名は3-30桁の数字、英字、アンダースコアを組み合わせたもののみ使用できます',
    'Please input correct password'                                                                         => 'パスワードの長さは6-30文字の範囲でなければなりません，スペースを含めることはできません',
    'Password is too weak'                                                                                  => 'パスワードが単純すぎます，再入力してください',
    'The two passwords you entered did not match'                                                           => '2 回入力されたパスワードが一致しません',
    'Please input correct website'                                                                          => 'サイト名の入力が正しくありません',
    'The current PHP %s is too low, please use PHP %s or higher'                                            => '現在のバージョンPHP %sが低すぎます，を使用してくださいPHP %s以上のバージョンを使用してください',
    'PDO is not currently installed and cannot be installed'                                                => '現在有効になっていませんPDO，インストールを実行できません',
    'The current permissions are insufficient to write the file %s'                                         => '現在の権限が不足しています，ファイルに書き込むことができません%s',
    'Please go to the official website to download the full package or resource package and try to install' => '現在のコードにはコアコードのみが含まれています，公式サイトから完全パッケージまたはリソースパッケージをダウンロードして上書きしてから再度インストールをお試しください',
    'The system has been installed. If you need to reinstall, please remove %s first'                       => '現在すでにインストールが完了しています，再インストールが必要な場合は，手動で削除してください%sファイル',
];
